### ISSUE TITLE
Search results are truncated

### ISSUE THREAD

**Issue by macmike** [awslabs/aws-serverless-twitter-event-source#1]
Since twitter lifted the character count from 140 to 280 the search api (and others) now require the parameter **tweet_mode** set with value **extended** on queries otherwise all of the result text is truncated.

**Comment by jlhood** [comment]
Apologies for the delayed response on this. I really appreciate you reporting the issue. I have a PR up to rewrite this app in python and have addressed this issue as a part of it.

**Comment by jlhood** [comment]
This issue has been fixed in v2 of this app. You can upgrade to v2 to pick up that change.
