### ISSUE TITLE
Python 3.6 Lambda EOL

### ISSUE THREAD

**Issue by michidk** [awslabs/aws-serverless-twitter-event-source#9]
The template deploys a Lambda running Python 3.6 (https://github.com/awslabs/aws-serverless-twitter-event-source/blob/master/template.yml#L42) which is currently being faded out.

> We are ending support for Python 3.6 in AWS Lambda. This follows Python 3.6 End-Of-Life (EOL) reached on December 23, 2021 [1].
> 
> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting July 18, 2022, Lambda will no longer apply security patches and other updates to the Python 3.6 runtime used by Lambda functions, and functions using Python 3.6 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Python 3.6 runtime. Starting August 17, 2022, you will no longer be able to update existing functions using the Python 3.6 runtime.
> 
> We recommend that you upgrade your existing Python 3.6 functions to Python 3.9 before August 17, 2022.
> 
> End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

It is advised to upgrade the function to Python 3.9.

**Comment by valerena** [comment]
Fixed by #10
